"""Add avatar_url column to user table

Revision ID: 69883961cdbf
Revises: 
Create Date: 2024-07-25 04:05:28.459342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69883961cdbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
